### ISSUE TITLE
imagej headless TypeError

### ISSUE THREAD

**Issue by samz417** [mpinkert/Notebooks#1]
Hi,

Looking to use the framework to run a script to implement imagej autolocal thresholding in python machine learning script. After first several run throughs with the jupyter notebook, everything worked fine, however starting this weekend, I began receiving the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-00250afb6b44> in <module>
      4 
      5 # Rigid Registration does not have a headless version.  You need to specify that ImageJ will NOT be operating in headless mode.
----> 6 ij = imagej.init('C:\\FIJI\\fiji-win64\\Fiji.app\\', headless=False)
      7 print("Finished.")

TypeError: init() got an unexpected keyword argument 'headless'

The same error is reflected in my own notebooks.

**Comment by mpinkert** [comment]
Hi Sam,

Just to understand, this code was running correctly previously?  Are you running on the same environment? 

Otherwise, I think the problem may be the \ characters.  Can you try changing them to / and see if that fixes it?  The \ character in strings makes special characters and so copy-pasting the windows path will fail.  You have three options to fix it.

1. Replace \ with /
2. Replace \ with \\ 
3. add an r before the string, which says it's a raw string.  E.g. r'C:\This\Is\A\Path'

Best,
Michael

**Comment by samz417** [comment]
Hi Michael,

The code below was functioning previously as shown. 

`# The specified fiji install does not seem to ship with rigid registration plugin.  I directed it to my local install.  Just replace the path with the one to your own.
import imagej
#ij = imagej.init('sc.fiji:fiji')`

`# Rigid Registration does not have a headless version.  You need to specify that ImageJ will NOT be operating in headless mode.
ij = imagej.init('C:\\FIJI\\fiji-win64\\Fiji.app\\', headless=False)`

I have also tried all three of your suggestions, and none of them changed the output. I still receive the following:

> ---------------------------------------------------------------------------
>TypeError                                 Traceback (most recent call last)
><ipython-input-11-4219601423fd> in <module>
>      4 
>      5 # Rigid Registration does not have a headless version.  You need to specify that ImageJ will >NOT be operating in headless mode.
>----> 6 ij = imagej.init(r'C:\FIJI\fiji-win64\Fiji.app', headless=False)

>TypeError: init() got an unexpected keyword argument 'headless'

**Comment by mpinkert** [comment]
Hi Sam,

If the code was working (as in, you were using ij in the gui mode and were able to run the rigid registration plug), then are you sure you are running in the correct environment?  You may have multiple environments on your computer.

Best,
Michael

**Comment by samz417** [comment]
Hi Michael,

Yes, I am using anaconda3 with the same virtual environment as used earlier. I am using conda version 4.7.10 conda-build version 3.4.1 and python version 3.6.4. Here are some details from conda info
>active environment : ComputerVision
    active env location : 
            shell level : 2
       user config file :
 populated config files : 
          conda version : 4.7.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       virtual packages :
       base environment : C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64  (read only)
               platform : win-64
             user-agent : conda/4.7.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
>
After opening an anaconda prompt and activating my virtual environment, I open a jupyter notebook in the directory where I have saved the notebook from this github. I ran the notebook and all the cells executed previously, and it did rigid registration in a gui window. The script has since stopped working.

**Comment by mpinkert** [comment]
Hi Sam,

Could you try sharing your script then?  I will try to run it and see if it's something wrong with the script or the environment.   I've run my own example script and I was able to start ImageJ in headless mode with no problem, so I'd need to look at your code to understand more.

I am a little confused what the problem could be though if you were able to successfully run it before.  Did you update the environment in any way between now and then?

Best regards,
Michael

**Comment by samz417** [comment]
The script is the same as the notebook here [https://github.com/mpinkert/Notebooks/blob/master/Examples/Rigid%20registration%20with%20pyimagej.ipynb](https://github.com/mpinkert/Notebooks/blob/master/Examples/Rigid%20registration%20with%20pyimagej.ipynb)

**Comment by mpinkert** [comment]
Hi Sam,

Then it has to be an issue with the environment or your installation of Fiji, as I was able to run the script.  Here are the versions I have installed.  What are yours?

jgo                0.2.0
jrun               0.1.0.dev0
pyimagej           0.4.0
pyjnius            1.1.2.dev0

**Comment by samz417** [comment]
Hi Michael,

Thanks for all the help. I must have run an update which removed these packages. I will try installing them again and running it.

Sam

**Comment by samz417** [comment]
Hi Michael,

I have these versions of the packages running, and I am receiving the same error, even after restarting with a fresh notebook instance. I am not sure if they have been updated because of other packages.
jgo 0.4.0
jrun 0.1.1
pyimagej 0.4.0
pyjnius 1.2.0

I don't seem to be able to pip install the versions you are using, so it will take some time to install from the source packages. Thanks again for your help.

Sam

**Comment by mpinkert** [comment]
Hi Sam,

I believe it is best practice to install pyimageJ, and then all these dependencies will be installed for you.  I think things might break (as you are witnessing) if they are installed separately.

Sorry I'm not more helpful; this issue is stumping me as well.

You may want to take this issue to the pyimagej issue tracker if it persists, as they will be more on top of issues with the plugin itself and the dependencies.  I don't know much about jgo/jrun or pyjnius.

Best,
Michael

**Comment by samz417** [comment]
Issue resolved after clean install of conda and pyimagej. Still not sure what happened to cause the issue at first.

**Comment by samz417** [comment]
Hi Michael,

Thanks for the help. Just wondering, is development on the python imagej
api still ongoing? I am interested in using it but have found current
documentation sparse at best.

Sam
sami.znati.17@ucl.ac.uk

**Comment by mpinkert** [comment]
I don't know if we're currently working on improving it.  If you have any suggestions or needs please submit an issue at the pyimagej github page!  https://github.com/imagej/pyimagej
